### ISSUE TITLE
Cannot move horizontally while rising in jump

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#1]
Expected behavior:
Hit jump
Hit left or right
obj_player moves left or right while moving upward

Observed bevahior:
Hit jump
Hit left or right
obj_player continues to move vertically

Notes:
Character _does_ move left or right while falling in jump
This is reproducible

@jbussing testing issue/bug filing; any thoughts/feedback on this format?

**Comment by jbussing** [comment]
Yep this was as expected per the code written from https://github.com/sohomsahaun/SnowState/tree/master/objects/oPlayerD.
But I implemented a more generic struct to handle a generic FSM for movement that could then be overridden by a given object for more features like a "win" and "dead" state. The next push has this code but also removes the jump and apply gravity which will be implemented in the next push.
