### ISSUE TITLE
Jittery movement (or low frame rate?)

### ISSUE THREAD

**Issue by eddivita** [mrbwaters/fire_drill#13]
Player movement is not smooth.  

Might be a frame rate/performance issue, or might be related to how movement updates are coded.

**Comment by mrbwaters** [comment]
Hmm. I'm not observing much jitter.

I've added a debugging feature (you can also use the debugger for this). Hit BACKSPACE to set "testing" in meta_game to true - this will draw the current frame rate in the upper left. Looks like it's ~1000 on my machine right now. As long as it's well above 60, we shouldn't observe any frames dropping.

I am noticing other bugs. Like the player getting "caught" on things that it should slide past.

Can you make a screen recording of the jitter you're observing?

**Comment by mrbwaters** [comment]
Note: the feature I described is in my latest commit on the branch "second-level." Feel free to test on there and merge when ready :)

**Comment by eddivita** [comment]
I was able to smooth things a little by rounding the player position to integers at the end of each movement and adding a change to the game canvas draw command.  I still get a little bit of jumpiness on my screen, but it might just be the speed of the objects vs. the monitor refresh rate.  Seem to work better when I scale down the movement rates slightly.  

Not sure if this is still an "issue", and I agree, I don't think it was a frame rate issue.
