### ISSUE TITLE
PC jitters when walking into wall

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#19]
[I made this Loom to help illustrate a few bugs I've observed](https://www.loom.com/share/c3ce8d4fb086403795579444e0b9b219).

1. PC jitters when walking into wall.
2. Top of ladder behavior is a little odd (might be improved with better level design).
3. I cannot reproduce but my PC got stuck on a piece of wall at some point.

**Comment by mrbwaters** [comment]
Following up on #2:
I've improved the level design so that the ladder doesn't terminate into nothing.
![image](https://user-images.githubusercontent.com/46800710/147678851-3b165ecc-c84b-424b-9674-3a0276e3760f.png)

The problem now is that the top of the ladder behaves like a hole when running on top of it (not climbing). 

Instead, I suggest it behave like the ground.

So in this case, the pc should climb to the top, get off the ladder, and then be able to run around on the platform as if it were solid ground. Unless, while standing on the ladder, the player hits down.

What do you think @jbussing?

**Comment by jbussing** [comment]
The overall jitters could be the result of some quick and dirty collision checks i make throughout the various state functions, but i also like this concept you propose here and will implement it

**Comment by jbussing** [comment]
I think this is fixed from earlier but this issues should be resolved after https://github.com/mrbwaters/fire_drill/pull/32 is merged

**Comment by mrbwaters** [comment]
Nice!
