### ISSUE TITLE
PC cannot run while riding a platform

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#20]
Expected:
Travel with platform and also add your own hspd via run input.

Observed:
Can only jump, not run, while on platform.

**Comment by mrbwaters** [comment]
Hmm. Actually, this bug seems to be sporadic. I definitely got stuck on a platform at least once. But it seems that you can run normally most of the time 🤔 

We'll have to do more investigation.

**Comment by jbussing** [comment]
I had to do some variable resetting when jumping from idle on a moving platform so as to now carry the hspd momentum into the jump, I might have to do the same for transitioning to the run state from idle on a moving platform. 

The stuck bug could also be the result of a quick and dirty collision I'm making to determine when im on a moving platform.

@mrbwaters would you mind taking a look at my references to "place_meeting()" within each state function to see if you could clean up the collision logic?

**Comment by mrbwaters** [comment]
I haven't seen this in a while so going to close.
