### ISSUE TITLE
PC pops on top of moving platform when caught between it and the wall

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#21]
Context:
PC is idle beside a wall.
obj_platform_move moves toward pc, pushing it into the wall

When the pc can no longer move, it pops on top of platform.
This isn't a bug, per se, but we should think about what SHOULD happen here.

I think it's time to introduce PC death!
@jbussing @theRealThagomizer

**Comment by jbussing** [comment]
I think @theRealThagomizer wanted to have a goomba-adjacent enemy so death is a reasonable state to add

**Comment by mrbwaters** [comment]
I agree that this should be a death condition.

In early levels, I think we can get around with added difficulty by not putting moving platforms in a place where the character can be squished by them. 

So this is partially solved by smart level design @theRealThagomizer @AllSystemsRGeorge

**Comment by jbussing** [comment]
the PC is now squishy!!!! Line 30 in scr_player_idle()
https://github.com/mrbwaters/fire_drill/pull/38
