### ISSUE TITLE
PC gets stuck on ladder at bottom of ladder

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#23]
Climb ladder.
Get to bottom.
Try to run left/right.
PC is stuck in Climb and cannot Run.

This might be a regression due to @eddivita's latest commits.

**Comment by mrbwaters** [comment]
There seems to be related issue at the top of the ladder!

**Comment by jbussing** [comment]
This should be solved with the newest collision re-factor. Lemme know.
