### ISSUE TITLE
PC gets stuck on moving platform

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#26]
[Really rough regression here](https://www.loom.com/share/9a7bcf4f006145b29c0b6dd0a7bb7e06).

The good news is that it now seems to be fully reproduceable. And that means it can be fixed!

**Comment by jbussing** [comment]
this is due to the lack of applied gravity to the PC and should be fixed with the next push

**Comment by mrbwaters** [comment]
With #32 [this issue has evolved](https://www.loom.com/share/e22daae1ae404c3caf79905be01c0f4f).

My guess from the observed behavior is that we only look for collisions with the moving platform when IDLE/FALL and not when RUN or JUMP.

**Comment by eddivita** [comment]
I think I fixed this by switching the target for the step collision check to meta_collision (parent of walls and moving platforms).  Still has some jitteriness with horizontal collisions, but seems like behavior with moving platforms is getting closer to desired behavior.

**Comment by mrbwaters** [comment]
Nice fix!
