### ISSUE TITLE
PC floats when sprite size is reduced from 16x16

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#30]
In my most recent PR, I shrank the sprite and collision mask of the pc to allow it to fit between blocks more easily. 

Now the PC hovers 2 pixels above the ground and collides with walls 2 pixels away on the right.

I infer that the collisions for the PC are based off the assumption that its sprite is 16x16 pixels rather than the actual collision mask.

Is there a reason for this?

**Comment by eddivita** [comment]
The transition from falling to idle checks for a wall or ladder 1 grid size below the player.  Since the sprites origin is in the upper left, this measures beyond the size of the sprite and thus the player seems to float.

**Comment by mrbwaters** [comment]
I figured.

Seems like we should refactor that collisions/transition code to something more stable.

Let’s discuss tonight.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by eddivita** [comment]
Quick fix applied to this branch.

**Comment by jbussing** [comment]
If the issue is fixed, can we close out the issue?

**Comment by mrbwaters** [comment]
Yes!
