### ISSUE TITLE
Menu selection moves too quickly when using analog stick on gamepad

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#34]
Because analog stick does not have a check_pressed function, every frame that the stick is held moves the highlight from one item to another. The result is that it jumps around super quick.

[A potential fix is in this thread but I'm deprioritizing the fix for now for time](https://www.reddit.com/r/gamemaker/comments/3zd1nt/gamepad_analog_stick_pressed/).

**Comment by eddivita** [comment]
Could apply a cooldown timer to ignore input within a certain time internval.

**Comment by mrbwaters** [comment]
Fixed in #67
