### ISSUE TITLE
Player has incorrect speed when riding on platform that doesn't have default speed.

### ISSUE THREAD

**Issue by eddivita** [mrbwaters/fire_drill#37]
Idle applies default platform speed instead of reading current speed from specific platform that player is colliding with.

**Comment by eddivita** [comment]
@jbussing

**Comment by jbussing** [comment]
🐛fix in https://github.com/mrbwaters/fire_drill/pull/38

**Comment by mrbwaters** [comment]
@eddivita Do you mind confirming the fix and then closing the issue?
