### ISSUE TITLE
Player does not enter fall state if walks off ledge

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#4]
Expect behavior:
Player enters "fall" state when falling.

Observed behavior:
Player enters fall state when on fall half of jump.
Player does NOT enter fall state when walking off of a platform and falling to lower ground.

@jbussing

**Comment by jbussing** [comment]
I will own this fix 😁

**Comment by mrbwaters** [comment]
This issue (or a related one) persists.

When walking off a ledge (but not ladders), player can still jump (even though they're in the air), and when they hit the ground they do not produce dust.

They may be in fall state but the on_ground state seems to be set incorrectly.

**Comment by jbussing** [comment]
🤔 There is a lot happening in the player engine now which makes the debugging a little challenging.I may want to re-work some things, especially as it relates to the on_ground variable, which seems like a "state" and should probably be re-incorporated into the logic in some other way. We should probably imply that states.idle == on_ground and that on_ladder == states.climb.

This way we should always be returning to idle. Or transitioning from either jump, run, fall, and climb

**Comment by eddivita** [comment]
There are some cases where you can be on_ground but not idle - obvious case is if you are running, but also can happen at bottom of a ladder, where the player should be climbing not idle.  Similarly, you can be on_ladder but not climbing if you have just jumped off of the ladder, as long as the player is still holding down the space bar.

**Comment by mrbwaters** [comment]
Hmm.

I think it would be helpful for us to sync and outline the entire player fsm.

I could imagine a state for talking to NPCs as well. And there are probably other states that will emerge as we go.

Do y'all have time today or tomorrow to hop on Discord and discuss?

Sent via Superhuman ( ***@***.*** )

**Comment by jbussing** [comment]
Yes i think we should sync.

Also would it help those edge cases if we store/remember the previous
state. Like if last state was climb and your vspd and hspd are 0 you are
back to idle but on the ladder.

Similarly, if the last state was fall before a collision, play thud noise.

And if the last state was not jump you can be allowed to jump, like jumping
from a climb, ladder, idle, or run.

Im also a fan of not fixing things that aren't broken, but I hope this
helps explain how the alternative would work.

**Comment by jbussing** [comment]
I can hop on tonight after dinner, or before lunch tomorrow.

**Comment by mrbwaters** [comment]
Tonight after dinner (what time is that?) is better for me cuz I’ll be driving tomorrow morning.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by jbussing** [comment]
I can do 7:30

**Comment by eddivita** [comment]
7:30 is good for me too!

**Comment by mrbwaters** [comment]
I thinkI can do 7:30pm as well.

It’s a date!

Sent via Superhuman iOS ( ***@***.*** )

**Comment by jbussing** [comment]
This should finally happen now in https://github.com/mrbwaters/fire_drill/pull/18
Also, the player can now match hspd on a moving platform 😁

**Comment by mrbwaters** [comment]
Resolved
