### ISSUE TITLE
PC has a tough time getting off the top off ladders

### ISSUE THREAD

**Issue by mrbwaters** [mrbwaters/fire_drill#66]
Gets stuck on them
Sometimes lifts off ~1 px above them

https://www.loom.com/share/b8eff0c91ec043a4810fa0d19c157430

@jbussing 
@eddivita

**Comment by mrbwaters** [comment]
Still an issue after #68 @jbussing

**Comment by jbussing** [comment]
fixed in https://github.com/mrbwaters/fire_drill/pull/71

**Comment by jbussing** [comment]
https://github.com/mrbwaters/fire_drill/pull/74

**Comment by mrbwaters** [comment]
Boom baby
